// Generated by gencpp from file tkdnn_ros/batchBbox.msg
// DO NOT EDIT!


#ifndef TKDNN_ROS_MESSAGE_BATCHBBOX_H
#define TKDNN_ROS_MESSAGE_BATCHBBOX_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sensor_msgs/Image.h>
#include <tkdnn_ros/bbox.h>

namespace tkdnn_ros
{
template <class ContainerAllocator>
struct batchBbox_
{
  typedef batchBbox_<ContainerAllocator> Type;

  batchBbox_()
    : img_processed()
    , batchBbox()
    , latency(0)  {
    }
  batchBbox_(const ContainerAllocator& _alloc)
    : img_processed(_alloc)
    , batchBbox(_alloc)
    , latency(0)  {
  (void)_alloc;
    }



   typedef  ::sensor_msgs::Image_<ContainerAllocator>  _img_processed_type;
  _img_processed_type img_processed;

   typedef std::vector< ::tkdnn_ros::bbox_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::tkdnn_ros::bbox_<ContainerAllocator> >::other >  _batchBbox_type;
  _batchBbox_type batchBbox;

   typedef int32_t _latency_type;
  _latency_type latency;





  typedef boost::shared_ptr< ::tkdnn_ros::batchBbox_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tkdnn_ros::batchBbox_<ContainerAllocator> const> ConstPtr;

}; // struct batchBbox_

typedef ::tkdnn_ros::batchBbox_<std::allocator<void> > batchBbox;

typedef boost::shared_ptr< ::tkdnn_ros::batchBbox > batchBboxPtr;
typedef boost::shared_ptr< ::tkdnn_ros::batchBbox const> batchBboxConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tkdnn_ros::batchBbox_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tkdnn_ros::batchBbox_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tkdnn_ros::batchBbox_<ContainerAllocator1> & lhs, const ::tkdnn_ros::batchBbox_<ContainerAllocator2> & rhs)
{
  return lhs.img_processed == rhs.img_processed &&
    lhs.batchBbox == rhs.batchBbox &&
    lhs.latency == rhs.latency;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tkdnn_ros::batchBbox_<ContainerAllocator1> & lhs, const ::tkdnn_ros::batchBbox_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tkdnn_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::tkdnn_ros::batchBbox_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tkdnn_ros::batchBbox_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tkdnn_ros::batchBbox_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tkdnn_ros::batchBbox_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tkdnn_ros::batchBbox_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tkdnn_ros::batchBbox_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tkdnn_ros::batchBbox_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7652717954f28f2eeb1b5b5103c7ab8b";
  }

  static const char* value(const ::tkdnn_ros::batchBbox_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7652717954f28f2eULL;
  static const uint64_t static_value2 = 0xeb1b5b5103c7ab8bULL;
};

template<class ContainerAllocator>
struct DataType< ::tkdnn_ros::batchBbox_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tkdnn_ros/batchBbox";
  }

  static const char* value(const ::tkdnn_ros::batchBbox_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tkdnn_ros::batchBbox_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sensor_msgs/Image img_processed\n"
"bbox[] batchBbox\n"
"int32 latency\n"
"================================================================================\n"
"MSG: sensor_msgs/Image\n"
"# This message contains an uncompressed image\n"
"# (0, 0) is at top-left corner of image\n"
"#\n"
"\n"
"Header header        # Header timestamp should be acquisition time of image\n"
"                     # Header frame_id should be optical frame of camera\n"
"                     # origin of frame should be optical center of camera\n"
"                     # +x should point to the right in the image\n"
"                     # +y should point down in the image\n"
"                     # +z should point into to plane of the image\n"
"                     # If the frame_id here and the frame_id of the CameraInfo\n"
"                     # message associated with the image conflict\n"
"                     # the behavior is undefined\n"
"\n"
"uint32 height         # image height, that is, number of rows\n"
"uint32 width          # image width, that is, number of columns\n"
"\n"
"# The legal values for encoding are in file src/image_encodings.cpp\n"
"# If you want to standardize a new string format, join\n"
"# ros-users@lists.sourceforge.net and send an email proposing a new encoding.\n"
"\n"
"string encoding       # Encoding of pixels -- channel meaning, ordering, size\n"
"                      # taken from the list of strings in include/sensor_msgs/image_encodings.h\n"
"\n"
"uint8 is_bigendian    # is this data bigendian?\n"
"uint32 step           # Full row length in bytes\n"
"uint8[] data          # actual matrix data, size is (step * rows)\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: tkdnn_ros/bbox\n"
"int32 x0\n"
"int32 x1\n"
"int32 y0\n"
"int32 y1\n"
"int32 cl\n"
;
  }

  static const char* value(const ::tkdnn_ros::batchBbox_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tkdnn_ros::batchBbox_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.img_processed);
      stream.next(m.batchBbox);
      stream.next(m.latency);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct batchBbox_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tkdnn_ros::batchBbox_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tkdnn_ros::batchBbox_<ContainerAllocator>& v)
  {
    s << indent << "img_processed: ";
    s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.img_processed);
    s << indent << "batchBbox[]" << std::endl;
    for (size_t i = 0; i < v.batchBbox.size(); ++i)
    {
      s << indent << "  batchBbox[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::tkdnn_ros::bbox_<ContainerAllocator> >::stream(s, indent + "    ", v.batchBbox[i]);
    }
    s << indent << "latency: ";
    Printer<int32_t>::stream(s, indent + "  ", v.latency);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TKDNN_ROS_MESSAGE_BATCHBBOX_H
